### ISSUE TITLE
Missing release notes

### ISSUE THREAD

**Issue by hoschi** [stampit-org/stamp#40]
`@stamp/XX` packages changed from my version 0.2.5 to latest 1.0.1, but I can't find what changed or where to look for this. Checked for `CHANGLELOG.md` in this repo and the Github release section.

**Comment by koresar** [comment]
Sorry. I forgot.
But there are no changes at all. Just SemVer version bump from 0.x (experimental) to 1.0 (stable).

Do you know how to maintain that information in a monorepo?

**Comment by hoschi** [comment]
@koresar thanks for the info, good to know :grinning: 

I created my first mono repo only some weeks ago, so: no I have no solution for this. I updated recompose as well and they put all together which is hard to read, imo :disappointed: 
https://github.com/acdlite/recompose/releases

If there is no changelog generator for this kind of stuff, the easiest solution I can think of is a pre commit hook which check the changed files and prefixes the message with the package names.

**Comment by koresar** [comment]
Any change log generators for monorepos you know?

**Comment by hoschi** [comment]
No, sorry. As I said its also new for me https://github.com/hoschi/yode
