### ISSUE TITLE
staticPropertyDescriptors vs staticDeepProperties

### ISSUE THREAD

**Issue by mlrsoft** [stampit-org/stamp#50]
In the stampit API, under [Static property descriptors](https://stampit.js.org/api/static-property-descriptors), the examples shows:

```javascript
let MyStamp = stampit() // empty stamp creates empty objects

MyStamp.name === 'Stamp' // every stamp default name is "Stamp"

MyStamp = MyStamp.staticDeepProperties({
  name: { value: 'MyStamp' } // this meta data will be applied just after composition, i.e. immediately
})

MyStamp.name === 'MyStamp'
```
I think it should be 

```javascript
let MyStamp = stampit() // empty stamp creates empty objects

MyStamp.name === 'Stamp' // every stamp default name is "Stamp"

MyStamp = MyStamp.staticPropertyDescriptors({
  name: { value: 'MyStamp' } // this meta data will be applied just after composition, i.e. immediately
})

MyStamp.name === 'MyStamp'
```
The same goes for the examples under  **Other ways to add static property descriptors**

**Comment by koresar** [comment]
Thank you very much for the issue.

A moment ago I found that Gitbook have blocked my account! I can't edit anything until I pay. Although, I'm on a free plan and they promised me that stampit OSS project will be always free.

I'll fix it as soon as they unblock my account.

**Comment by koresar** [comment]
Fixed. 👍
