### ISSUE TITLE
Fix `@stamp/core/mergeOne()` not correctly handling properties with the value `undefined`

### ISSUE THREAD

**Issue by PopGoesTheWza** [stampit-org/stamp#56]
Current implementation of `@stamp/core/mergeOne()` when hitting an `src` property with the value `undefined` simply `return`s (thus returning a final merged result of `undefined`. Code should be altered so that it `continue`s the loop and compute the correct merged result.

- `stamp/packages/collision/index.js` line 30

This issue relates with #52

**Comment by koresar** [comment]
Can't find what you mean in the `stamp/packages/collision/index.js:30` file.

**Comment by PopGoesTheWza** [comment]
@koresar I likely fumbled with the reference with/in collision.

Fact is you already have the fix identified (changing `return` to `continue` in `mergeOne()`

**Comment by koresar** [comment]
Then closing this issue as (soon to be) Done
