### ISSUE TITLE
Should `@stamp` support be limited to NodeJS? And if so which version?

### ISSUE THREAD

**Issue by PopGoesTheWza** [stampit-org/stamp#57]
In article [Fun with Stamps. Episode 20. Stampit v4](https://medium.com/@koresar/fun-with-stamps-episode-20-stampit-v4-9a043a36a984) it is mentioned:

> `stampit` is mainly for browsers. It has both node and browser builds. Whereas `@stamp/it` is node CommonJS only.

This is mentioned **nowhere** in any of the `README.md` of the `@stamp` monorepo.

Furthermore, current `package.json` requires a node engine `>= 6.4.0` and `.travis.yml` setup test against node version 6, 7, 8, 10 and 12, but NodeJS [Releases page](https://nodejs.org/en/about/releases/) no longer lists version 6 and 7.

By defining the minimal supported NodeJS version, we define the proper ES version to expect and can clean/simplify/harden the code base in several places (get rid of `__proto__`, rely on `Symbol`, `Reflect` and `Proxy` primitives, spread and rest operators, etc.)

NodeJS version | Supported ES version
--- | ---
6.4.0 | ES2015
*7.5.0* | *ES2016*
8.6.0 | ES2016 (and parts of ES217)
*9.11.2* | *ES217*
10.3.0 | ES2018

Also, since odd numbered releases of NodeJS are not considered long-lived, `.travis.yml` might be better limited to testing only even numbered version plus:

- an odd numbered version if it is the officially minimum supported version (i.e. `>= 7.5.0` in `package.json`)
- the latest odd numbered version (if user base requires "cutting-edge' NodeJS support (like current version 13)

[source: node.green](https://node.green/)

**Comment by koresar** [comment]
Agree. Time to drop non LTS node versions. Feel free to action.

**Comment by PopGoesTheWza** [comment]
I can PR with node >= 8.6.0 in package.json and travis to run tests on 8, 10 and 12 (NodeJS 13 is currently not fresh enough to bother with)

Following this, additional PRs could come to incrementally bring code base to ES2016

**Comment by koresar** [comment]
Superb. 
https://www.youtube.com/embed/ZXsQAXx_ao0
