### ISSUE TITLE
Please explain this use of `bind()` without any argument at the end of `@stamp/it`

### ISSUE THREAD

**Issue by PopGoesTheWza** [stampit-org/stamp#76]
https://github.com/stampit-org/stamp/blob/90558ea3d3c49d7fe0e06c84be0f03b57e9627c4/packages/it/index.js#L100

**Comment by koresar** [comment]
I don't exactly recall. But I think tests fail without it. Do they?

**Comment by koresar** [comment]
Oh. I remember now.
The "compose" function should compose "this" context into the stamp it creates. The binding makes sure that "this === undefined".

**Comment by PopGoesTheWza** [comment]
So `somefunction.bind()` is similar to `somefunction.bind(undefined)` I believe?

And we are adding a wrapping around `stampit.compose` since there is no other way to retrieve the **unbound** function, correct?

**Comment by koresar** [comment]
Correct
